config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users

  resources :projects do
    resources :memberships
    resources :tasks do
      resources :comments
    end
  end

  get 'about' => 'about#index'
  get 'faq' => 'common_questions#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :project

  validates :user_id, presence: true, uniqueness: {scope: :project_id, message: "was already added to this project."}

  enum role: {member: 0, owner: 1}

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  layout 'current_user_layout'

  before_action :set_project
  before_action :task_member_of?
  before_action :last_owner?, only: [:index, :update]

  def index
    @membership = Membership.new
    @memberships = @project.memberships.all
    @project = Project.find(params[:project_id])
    # owner is defined if current user is project owner
    if current_user == @project.memberships.find_by(role: 1).user
      @owner = current_user
    end
    # project must have at least one owner
    if @owners_count == 1
      @last_owner = @memberships.where(role: 1)
    end
  end

  def create
    @membership = Membership.new(membership_params)
    @membership.project_id = @project.id

    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.fullname} was successfully added"
    else
      flash.now[:alert] = @membership.errors.full_messages
      render :index
    end
  end

  def update
    @membership = Membership.find(params[:id])
    if @owners_count == 1 && @membership.role == "owner"
      redirect_to project_memberships_path(@project), alert: "Project must have at least one owner"
    elsif @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.first_name}\'s membership was successfully updated"
    else
      render :index
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    # different redirect paths if destroyer is current user or admin
    if @membership.user == current_user
      redirect_to projects_path(@membership.user), notice: "#{@membership.user.fullname} was successfully removed."
    else
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.fullname} was successfully removed."
    end
  end

  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  # projects must have at least one owner, this is owners count calculated here.
  def last_owner?
    @project = Project.find(params[:project_id])
    @owners_count = @project.memberships.where(role: 1).count
  end

end

app/views/memberships/_membership_errors_form.html.erb
<% if @membership.errors.any? %>
<div class= "alert alert-danger">
  <h2><strong>
    <%= pluralize(@membership.errors.count, "error") %> prohibited this task from being saved:
  </strong></h2>
  <ul>
    <% @membership.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/memberships/_new_membership_form.html.erb
<!-- only admins and project members will get to create new project memberships -->
<% if current_user.admin || @owner %>
  <div class= "well form-inline">
  <%= form_for [@project, @membership] do |f| %>
    <div class="form-group">
      <%= f.collection_select :user_id, User.all, :id, :fullname, {include_blank: 'Please select a user...'}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.select :role, Membership.roles.keys.map {|role| [role.titleize,role]}, {include_blank: false}, {class: "form-control"} %>
    </div>
      <button type="submit" class="btn btn-primary">Add New Member</button>
    <% end %>
  </div>
<% end %>

app/views/memberships/_project_memberships_form.html.erb
<!-- only project owners and admins will be able to change project memberships other than their own -->
<% if current_user.admin || @owner %>
  <div class= "form-inline">
    <% @project.memberships.each do |membership| %>
      <%= form_for [@project, membership] do |f| %>
      <div class="form-group col-md-2">
        <%= link_to membership.user.fullname, user_path(membership.user) %>
      </div>
      <div class="form-group col-md-2">
        <%= f.select :role, Membership.roles.keys.map {|role| [role.titleize,role]}, {include_blank: false}, class: "form-control" %>
      </div>
        <%= f.submit 'Update', class: 'btn btn-sm btn-primary' %>
      <div class="pull-right">
        <% if @last_owner && membership.role == "owner" %>
          You are the last owner.
        <% else %>
          <%= link_to project_membership_path(@project, membership), method: :delete do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        <% end %>
      </div>
<br><br>
      <% end %>
    <% end %>
  </div>
<!-- project members will only get to see project roles in static text but may delete their own -->
<% else %>
  <table class="table table-striped">
    <% @project.memberships.each do |membership| %>
      <tr>
        <td><%= link_to membership.user.fullname, user_path(membership.user) %></td>
        <td><%=  membership.role %></td>
        <% if membership.user == current_user || current_user.admin %>
          <td>
            <%= link_to project_membership_path(@project, membership), method: :delete do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/memberships/index.html.erb
<div class="page-header">
  <h1><%= @project.name %>: Manage Members</h1>
</div>

<ol class="breadcrumb">
  <li>
    <%= link_to 'Projects', projects_path %>
  </li>
  <li>
    <%= link_to @project.name, project_path(@project) %>
  </li>
  <li><class="active">
    Memberships
  </li>
</ol>

<%= render 'membership_errors_form' %>
<br>
<%= render 'new_membership_form' %>

<%= render 'project_memberships_form' %>