config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users

  resources :projects do
    resources :memberships
    resources :tasks do
      resources :comments
    end
  end

  get 'about' => 'about#index'
  get 'faq' => 'common_questions#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  belongs_to :project
  has_many :comments, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout 'current_user_layout'

  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :authenticate
  before_action :task_member_of?


  def index
    @tasks = @project.tasks.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id

    if @task.save
      redirect_to project_tasks_path(@project), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
      redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:description, :due_date, :complete, :project_id)
    end
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task], html: {class: 'form-horizontal'} do |f| %>

  <%= render partial: 'shared/errors', locals: {object: @task} %>

    <div class="form-group">
      <label class= "control-label col-md-2">
        <%= f.label :description %>
      </label>
      <div class= "col-md-4">
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>

    <div class= "form-group">
      <label class="control-label col-md-2">
        <%= f.label :due_date %>
      </label>
      <div class= "col-md-4">
        <%= f.date_select :due_date, class: 'form-control' %>
      </div>
    </div>

    <!-- checkbox will only show on tasks being edited -->
    <% if @task.description %>
    <div class= "form-group">
      <label class= "control-label col-md-2">
        Complete
      </label>
      <div class="col-md-4">
        <%= f.check_box(:complete) %>
      </div>
    </div>
    <% end %>

    <div class="form-group">
      <div class="actions col-md-offset-2 col-md-4">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'Cancel', project_tasks_path(@project), class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Edit Task</h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to @project.name, project_path(@project) %>
  <li><%= link_to @task.description, project_task_path(@project, @task) %>
  <li><class="active">
    Edit
  </li>
</ol>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class= "page-header">
  <div class="pull-right">
    <%= link_to 'New Task', new_project_task_path(@project), class: 'btn btn-info' %>
  </div>
  <h1>Tasks for <%= @project.name %></h1>
  <br>
  <ol class="breadcrumb">
    <li>
      <%= link_to 'Projects', projects_path %>
    </li>
    <li>
      <%= link_to @project.name, project_path(@project), id: 'proj' %>
    </li>
    <li><class="active">
      Tasks
    </li>
  </ol>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td>
        <%= link_to "#{task.description}", project_task_path(@project, task) %>
          <span class="badge"><%= "#{task.comments.count}" %></span>
      </td>
      <td>
        <%= task.complete %>
        <% if task.complete == nil %>
          <%= false %>
        <% end %>
      </td>
      <td><%= task.due_date.strftime("%m/%d/%Y") %></td>
      <td class="text-right">
        <%= link_to 'Edit', edit_project_task_path(@project, task), class: 'btn btn-info' %>
        <%= link_to project_task_path(@project, task), id: 'delete_link', method: :delete do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>Create a new task</h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to @project.name, project_path(@project) %>
  <li><class="active">
    New Task
  </li>
</ol>
<br>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path, class: 'btn btn-info' %>
    <%= link_to 'Delete', project_task_path(@project, @task), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <h1><strong><%= @task.description %></strong></h1>
</div>


<ol class="breadcrumb">
  <li>
    <%= link_to 'Projects', projects_path %>
  </li>
  <li>
    <%= link_to @project.name, project_path(@project) %>
  </li>
  <li>
    <%= link_to 'Tasks', project_tasks_path(@project) %>
  </li>
  <li><class="active">
    <%= @task.description %>
  </li>
</ol>

<b>Due on:</b>
  <%= @task.due_date.strftime("%m/%d/%Y") %>
<br>
<br>
<b>Complete:</b>
  <%= @task.complete %>
    <% if @task.complete == nil %>
      <%= false %>
    <% end %>
<br>
<br>

<h3>Comments</h3>
    <% @task.comments.each do |comment| %>
      <div class="row">
          <div class="col-md-3">
            <% if comment.user == nil %>
              <em>(deleted user)</em>
            <% else %>
              <%= link_to "#{comment.user.fullname}", user_path(comment.user) %>
            <% end %>
            <br>
            <p class="text-muted">
              <%= time_ago_in_words(comment.created_at) %>
            </p>
          </div>
          <div class="col-md-9">
            <%= comment.remark %>
          </div>
      </div>
<br>
    <% end %>

<br>

<%= form_for [@project, @task, @comment] do |f| %>
  <div class="col-md-9 col-md-offset-3">
      <%= f.text_area :remark, rows: 5, cols: 90 %>
      <br>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
<% end %>