config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users

  resources :projects do
    resources :memberships
    resources :tasks do
      resources :comments
    end
  end

  get 'about' => 'about#index'
  get 'faq' => 'common_questions#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true
  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'current_user_layout'

  before_action :authenticate
  before_action :member_of?, except: [:index, :new, :create]
  before_action :owner_of?, only: [:edit, :update, :destroy]

  def index
      @adminprojects = Project.all
      @memberships = Membership.where(user_id: current_user.id)
  end

  def show
    @project = Project.find(params[:id])
    if current_user.admin || @project.memberships.where(user_id: current_user.id)[0].role == "owner"
      @owner = current_user
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      # user is made project owner upon project creation
      @membership = Membership.new
        @membership.user_id = current_user.id
        @membership.project_id = @project.id
        @membership.role = 1
        @membership.save
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end

  end

  def update
    @project = Project.find(params[:id])
      if @project.update(project_params)
        redirect_to @project, notice: 'Project was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end

end

app/views/projects/_admin_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
      <% @adminprojects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: 'form-horizontal'}) do |f| %>

<%= render partial: 'shared/errors', locals: {object: @project} %>

<div class="form-group">
  <label class= "control-label col-md-2">
    <%= f.label :name %>
  </label>
  <div class= "col-md-4">
    <%= f.text_field :name, class: 'form-control' %>
  </div>
</div>

<div class="form-group">
   <div class="col-md-offset-2 col-md-3">
     <%= f.submit class: "btn btn-primary" %>
     <%= link_to 'Cancel', projects_path, class: 'btn btn-default' %>
   </div>
</div>
<% end %>

app/views/projects/_user_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %> </td>
        <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class= "page-header">
  <div class="pull-right">
    <%= link_to 'New project', new_project_path, class: 'btn btn-info' %>
  </div>
  <h1>Projects</h1>
</div>

<!-- admins see all projects, other users only see their own -->
<% if current_user.admin? %>
  <%= render 'admin_table' %>
<% else %>
  <%= render 'user_table' %>
<% end %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <% if @owner %>
      <%= link_to 'Edit', edit_project_path, class: 'btn btn-info' %>
    <% end %>
  </div>

  <h1><%= @project.name %></h1>
</div>

<br>
<ol class="breadcrumb">
  <li> <%= link_to 'Projects', projects_path %>
  <li><class="active">
    <%= @project.name %>
  </li>
</ol>
<br>
<br>
  <%= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project) %>
  <br>
  <br>
  <%= link_to pluralize(@project.memberships.count, "Members"), project_memberships_path(@project) %>
<br>
<br>
<% if @owner %>
  <div class="well">
    <h3>Delete</h3>
    <%= "Deleting this project will also delete #{pluralize(@project.memberships.count, "membership")}, #{pluralize(@project.tasks.count, "task")} and associated comments." %>
    <br>
    <br>
    <%= link_to 'Delete', project_path, method: :delete, class: 'btn btn-danger' %>
  </div>
<% end %>