config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users

  resources :projects do
    resources :memberships
    resources :tasks do
      resources :comments
    end
  end

  get 'about' => 'about#index'
  get 'faq' => 'common_questions#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peter Vliet Tasker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<!-- for Tasker marketing pages -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Tasker in navbar has different endpoints if user is logged in or not -->
          <% if current_user %>
            <a class="navbar-brand" href="/projects">Tasker</a>
          <% else %>
            <a class="navbar-brand" href="/">Tasker</a>
          <% end %>
          <!-- logged in user sees Projects and Users dropdowns -->
          <% if current_user %>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  Projects
                  <span class="caret"></span>
                </a>
              <ul class="dropdown-menu" role="menu">
                <% @projects.each do |project| %>
                  <li>
                    <%= link_to project.name, project_path(project) %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to 'New Project', new_project_path %>
                </li>
              </ul>
            </li>
              <li>
                <%= link_to 'Users', users_path %>
              </li>
            </ul>
          <% end %>
      </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
        <!-- logged in/out users see different options on right of navbar  -->
          <% if current_user %>
            <li> <%= link_to "#{current_user.first_name} #{current_user.last_name}", root_path %></li>
            <li> <%= link_to 'Sign Out', signout_path %></li>
          <% else %>
            <li><%= link_to 'Sign Up', signup_path %></li>
            <li><%= link_to 'Sign In', signin_path %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <center><%= notice %></center>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <center><%= alert %></center>
    </div>
  <% end %>

<%= yield %>

  </div>
<br>
<br>
<br>
<br>
<footer>
<div class= "container">
  <hr>
  <div class="row">
      <div class="col-md-6">
      <%= link_to "About", about_path %>
      |
      <%= link_to "Terms", terms_path %>
      |
      <%= link_to "FAQ", faq_path %>
      |
      <%= link_to "Users", users_path %>
      |
      <%= link_to "Projects", projects_path %>
    </div>
    <div class="col-md-6 text-right">
        <%= link_to image_tag('linkedin.jpg', class: "img-footer"), "https://www.linkedin.com/in/petervliet" %>
        <%= link_to image_tag('github.png', class: "img-footer"), "https://github.com/petevliet"  %>
        <%= link_to image_tag('twitter.png', class: "img-footer"), "https://twitter.com/Pete_Vliet" %>
        <%= link_to image_tag('galvanize.png', class: "img-footer"), "https://students.gschool.it/students/218" %>
    </div>
  </div>
</div>
</footer>

</div>
</body>
</html>

app/views/layouts/current_user_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskerPeter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<!-- this layout will only be seen by logged in users on non-marketing Tasker pages -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="/projects">Tasker</a>

            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  Projects
                  <span class="caret"></span>
                </a>
              <ul class="dropdown-menu" role="menu">
                <% @projects.each do |project| %>
                  <li>
                    <%= link_to project.name, project_path(project) %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to 'New Project', new_project_path %>
                </li>
              </ul>
            </li>
              <li>
                <%= link_to('Users', users_path, :id => 'users_link') %>
              </li>
            </ul>
      </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "#{current_user.first_name} #{current_user.last_name}", root_path %></li>
            <li> <%= link_to 'Sign Out', signout_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <center><%= notice %></center>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <center><%= alert %></center>
    </div>
  <% end %>

<%= yield %>

  </div>
<br>
<br>
<br>
<br>
<footer>
<div class= "container">
  <hr>
  <div class="row">
      <div class="text-center">
      <%= link_to "About", about_path %>
      |
      <%= link_to "Terms", terms_path %>
      |
      <%= link_to "FAQ", faq_path %>
      |
      <%= link_to "Users", users_path %>
      |
      <%= link_to "Projects", projects_path %>
    </div>
  </div>
</div>
</footer>

</div>
</body>
</html>